analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - linesman_lint:
      allowByDefault: false
      verbose: true
      rules:
        - type: allow
          source: test.dart
          target: import2.dart
