name: linesman
description: Don't cross the line
version: 0.1.0+1
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ^3.7.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  equatable: ^2.0.5
  fast_immutable_collections: ^11.0.4
  glob: ^2.1.2

dev_dependencies:
  lints: ^5.1.1
  strict: ^2.1.0
  test: ^1.24.0
