analyzer:
  plugins:
    - custom_lint
  exclude:
    - example/**

custom_lint:
  rules:
    - linesman_lint:
      verbose: true
      rules:
        - type: deny
          source: test.dart
          target: import1.dart
        - type: deny
          source: test.dart
          target: '*2.dart'
        - type: deny
          source: test.dart
          target: package:linesman_lint_example/import3.dart
        - type: deny
          source: '**'
          target: package:linesman_lint_example/import4.dart
        - type: deny
          source: '*.dart'
          target: package:linesman_lint_example/more_imports/*
        - type: deny
          source: '*.dart'
          target: package:linesman_lint_example/**/*.dart
