name: linesman_lint_example
description: Linesman lint example package
version: 0.1.0+1
publish_to: none
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ^3.7.0

dev_dependencies:
  custom_lint:
  linesman_lint:
    path: ..

dependency_overrides:
  linesman:
    path: ../../linesman
