name: linesman_lint_example
description: Linesman lint example package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  custom_lint:
  linesman_lint:
    path: ..

dependency_overrides:
  linesman:
    path: ../../linesman
