name: Test

on:
  push:
    branches:
      - main
      - ci-*
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart --version
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: bin/run-tests
